name: CD
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
      - name: Build
        run: |
          yarn
          yarn build
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GIT_DEPLOY_KEY }}
        run: |
          git config --global user.email "me@patrickwu.space"
          git config --global user.name "Jinming Wu, Patrick"
          git clone --depth 1 https://patrick330602:$GH_TOKEN@github.com/wslutilities/website.git website
          cp -rf ./.vuepress/dist/* ./website/wslu/
          git --git-dir=./website/.git --work-tree=./website add -A
          git --git-dir=./website/.git --work-tree=./website commit -m "wslu Wiki update at $(date)"
          git --git-dir=./website/.git --work-tree=./website push
