name: CD
on: [push]
jobs:
  build:
    name: Generate
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Install NodeJS
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: lts/*
      - name: Generate Wiki
        run: |
          npm install
          npm run build
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GIT_DEPLOY_KEY }}
        run: |
          git config --global user.email "me@patrickwu.space"
          git config --global user.name "Jinming Wu, Patrick"
          git clone --depth 1 https://patrick330602:$GH_TOKEN@github.com/wslutilities/wslutilities.github.io.git website
          cp -rf ./.vuepress/dist/* ./website/wslu/
          git --git-dir=./website/.git --work-tree=./website add -A
          git --git-dir=./website/.git --work-tree=./website commit -m "Wslu Wiki update at $(date)"
          git --git-dir=./website/.git --work-tree=./website push